This notebook spends a little time trying to get a basic feel for what's in the NVCS source tables through the lens of how we'll have to deal with the data in code.

In [64]:
import os
import pandas as pd
from IPython.display import display
from bis2 import dd
pd.set_option('display.max_colwidth', -1)

For now, I dumped the files here into the working code repo to deal with them locally. Eventually, we will want to put these into their own source code repo or somehow deal with the version control dynamic on the files. I output the file list here to see what all I'm dealing with.

In [2]:
os.listdir("./USNVC_DownloadMarch2017")

['UnitObsoleteParent.txt',
 'reference.txt',
 'unit.txt',
 'UnitXReference.txt',
 'UnitObsoleteName.txt',
 'UnitXEcoregionUsfs2007.txt',
 'UnitXSubnation.txt',
 'UnitPredecessor.txt',
 'UnitSubtype.txt',
 'd_usfs_ecoregion1994.txt',
 'NVCS_DB_Diagram.png',
 'UnitParentSubtype.txt',
 'unitDescription.txt',
 'd_dist_confidence.txt',
 'd_occurrence_status.txt',
 'UnitXSimilarUnit.txt',
 'USNVCdatabase_29July2017.pdf',
 'd_curr_presence_absence.txt',
 'UnitXEcoregionUsfs1994.txt',
 'd_subnation.txt',
 'NVCS DB Keys.pdf',
 'd_usfs_ecoregion_level.txt']

There might be more efficient ways of processing these data from text files, but I find Pandas pretty convenient to work with. It introduces a few issues of its own, but we are going to need to deal with the basic messiness of going from text dumps from an unknown backend database platform into what we can work with cleanly. These are Windows sourced files with CRLF line terminators, which seem to be the default for C engine Pandas. We might also need to handle detecting the encoding of the content a little better, but I found ISO-8859-1 to work, at least.

I went ahead and added in read of the unit descriptions table here as well for later use.

In [43]:
units = pd.read_csv("USNVC_DownloadMarch2017/unit.txt", sep='\t', encoding = "ISO-8859-1", dtype={"element_global_id":str,"parent_id":str})
print (units.dtypes)
display (units)

element_global_id            object
parent_id                    object
d_classification_level_id    int64
elementuid                   float64
classificationcode           object
databasecode                 object
status                       object
colloquialname               object
scientificname               object
formattedscientificname      object
translatedname               object
hierarchylevel               object
unitsort                     object
usstatus                     object
dtype: object

,element_global_id,parent_id,d_classification_level_id,elementuid,classificationcode,databasecode,status,colloquialname,scientificname,formattedscientificname,translatedname,hierarchylevel,unitsort,usstatus
0,860217,NaN,101,2.860217,1,C01,Accepted,Forest & Woodland,Mesomorphic Tree Vegetation Class,Mesomorphic Tree Vegetation Class,Mesomorphic Tree Vegetation Class,Class,1,CT
1,860211,NaN,101,2.860211,2,C02,Accepted,Shrub & Herb Vegetation,Mesomorphic Shrub & Herb Vegetation Class,Mesomorphic Shrub & Herb Vegetation Class,Mesomorphic Shrub & Herb Vegetation Class,Class,2,CT
2,860216,NaN,101,2.860216,3,C03,Accepted,Desert & Semi-Desert,"Xeromorphic Woodland, Scrub & Herb Vegetation Class","Xeromorphic Woodland, Scrub & Herb Vegetation Class","Xeromorphic Woodland, Scrub & Herb Vegetation Class",Class,3,CT
3,860213,NaN,101,2.860213,4,C04,Accepted,"Polar & High Montane Scrub, Grassland & Barrens","Cryomorphic Scrub, Herb & Cryptogam Vegetation Class","Cryomorphic Scrub, Herb &amp; Cryptogam Vegetation Class","Cryomorphic Scrub, Herb & Cryptogam Vegetation Class",Class,4,CT
4,860214,NaN,101,2.860214,5,C05,Accepted,Aquatic Vegetation,Hydromorphic Vegetation Class,Hydromorphic Vegetation Class,Hydromorphic Vegetation Class,Class,5,CT
5,860218,NaN,101,2.860218,6,C06,Accepted,Open Rock Vegetation,Cryptogam - Open Mesomorphic Vegetation Class,Cryptogam - Open Mesomorphic Vegetation Class,Cryptogam - Open Mesomorphic Vegetation Class,Class,6,CT
6,860232,860217,102,2.860232,1.A,S17,Accepted,Tropical Forest & Woodland,Tropical Forest & Woodland Subclass,Tropical Forest &amp; Woodland Subclass,Tropical Forest & Woodland Subclass,Subclass,1.A,CT
7,860227,860217,102,2.860227,1.B,S15,Accepted,Temperate & Boreal Forest & Woodland,Temperate & Boreal Forest & Woodland Subclass,Temperate &amp; Boreal Forest &amp; Woodland Subclass,Temperate & Boreal Forest & Woodland Subclass,Subclass,1.B,CT
8,860219,860211,102,2.860219,2.A,S01,Accepted,"Tropical Grassland, Savanna & Shrubland","Tropical Grassland, Savanna & Shrubland Subclass","Tropical Grassland, Savanna & Shrubland Subclass","Tropical Grassland, Savanna & Shrubland Subclass",Subclass,2.A,CT
9,860233,860211,102,2.860233,2.B,S18,Accepted,Temperate & Boreal Grassland & Shrubland,Temperate & Boreal Grassland & Shrubland Subclass,Temperate & Boreal Grassland & Shrubland Subclass,Temperate & Boreal Grassland & Shrubland Subclass,Subclass,2.B,CT
10,926082,860211,102,2.926082,2.C,S44,Accepted,Shrub & Herb Wetland,Shrub & Herb Wetland Subclass,Shrub &amp; Herb Wetland Subclass,Shrub & Herb Wetland Subclass,Subclass,2.C,CT
11,860224,860216,102,2.860224,3.A,S06,Accepted,"Warm Desert & Semi-Desert Woodland, Scrub & Grassland","Warm Desert & Semi-Desert Woodland, Scrub & Grassland Subclass","Warm Desert & Semi-Desert Woodland, Scrub & Grassland Subclass","Warm Desert & Semi-Desert Woodland, Scrub & Grassland Subclass",Subclass,3.A,CT
12,860228,860216,102,2.860228,3.B,S11,Accepted,Cool Semi-Desert Scrub & Grassland,Cool Semi-Desert Scrub & Grassland Subclass,Cool Semi-Desert Scrub & Grassland Subclass,Cool Semi-Desert Scrub & Grassland Subclass,Subclass,3.B,CT
13,860231,860213,102,2.860231,4.A,S16,Accepted,Tropical High Montane Scrub & Grassland,Tropical High Montane Scrub & Grassland Subclass,Tropical High Montane Scrub & Grassland Subclass,Tropical High Montane Scrub & Grassland Subclass,Subclass,4.A,CT
14,860229,860213,102,2.860229,4.B,S12,Accepted,Temperate to Polar Alpine & Tundra Vegetation,Temperate to Polar Alpine & Tundra Vegetation Subclass,Temperate to Polar Alpine &amp; Tundra Vegetation Subclass,Temperate to Polar Alpine & Tundra Vegetation Subclass,Subclass,4.B,CT
15,860226,860214,102,2.860226,5.A,S09,Accepted,Saltwater Aquatic Vegetation,Saltwater Aquatic Vegetation Subclass,Saltwater Aquatic Vegetation Subclass,Saltwater Aquatic Vegetation Subclass,Subclass,5.A,CT
16,860222,860214,102,2.860222,5.B,S13,Accepted,Freshwater Aquatic Vegetation,Freshwater Aquatic Vegetation Subclass,Freshwater Aquatic Vegetation Subclass,Freshwater Aquatic Vegetation Subclass,Subclass,5.B,CT
17,860220,860218,102,2.860220,6.A,S02,Accepted,Tropical Open Rock Vegetation,Tropical Open Rock Vegetation Subclass,Tropical Open Rock Vegetation Subclass,Tropical Open Rock Vegetation Subclass,Subclass,6.A,CT
18,860230,860218,102,2.860230,6.B,S04,Accepted,Temperate & Boreal Open Rock Vegetation,Temperate & Boreal Open Rock Vegetation Subclass,Temperate &amp; Boreal Open Rock Vegetation Subclass,Temperate & Boreal Open Rock Vegetation Subclass,Subclass,6.B,CT
19,860270,860232,103,2.860270,1.A.1,F003,Accepted,Tropical Dry Forest & Woodland,Tropical Dry Forest & Woodland Formation,Tropical Dry Forest &amp; Woodland Formation,Tropical Dry Forest & Woodland Formation,Formation,1.A.1,CT
20,860256,860232,103,2.860256,1.A.2,F020,Accepted,Tropical Lowland Humid Forest,Tropical Lowland Humid Forest Formation,Tropical Lowland Humid Forest Formation,Tropical Lowland Humid Forest Formation,Formation,1.A.2,CT
21,860262,860232,103,2.860262,1.A.3,F004,Accepted,Tropical Montane Humid Forest,Tropical Montane Humid Forest Formation,Tropical Montane Humid Forest Formation,Tropical Montane Humid Forest Formation,Formation,1.A.3,CT
22,860267,860232,103,2.860267,1.A.4,F029,Accepted,Tropical Flooded & Swamp Forest,Tropical Flooded & Swamp Forest Formation,Tropical Flooded & Swamp Forest Formation,Tropical Flooded & Swamp Forest Formation,Formation,1.A.4,CT
23,860239,860232,103,2.860239,1.A.5,F006,Accepted,Mangrove,Mangrove Formation,Mangrove Formation,Mangrove Formation,Formation,1.A.5,CT
24,860255,860227,103,2.860255,1.B.1,F018,Accepted,Warm Temperate Forest & Woodland,Warm Temperate Forest & Woodland Formation,Warm Temperate Forest &amp; Woodland Formation,Warm Temperate Forest & Woodland Formation,Formation,1.B.1,C
25,860241,860227,103,2.860241,1.B.2,F008,Accepted,Cool Temperate Forest & Woodland,Cool Temperate Forest & Woodland Formation,Cool Temperate Forest &amp; Woodland Formation,Cool Temperate Forest & Woodland Formation,Formation,1.B.2,C
26,860261,860227,103,2.860261,1.B.3,F026,Accepted,Temperate Flooded & Swamp Forest,Temperate Flooded & Swamp Forest Formation,Temperate Flooded & Swamp Forest Formation,Temperate Flooded & Swamp Forest Formation,Formation,1.B.3,C
27,860236,860227,103,2.860236,1.B.4,F001,Accepted,Boreal Forest & Woodland,Boreal Forest & Woodland Formation,Boreal Forest &amp; Woodland Formation,Boreal Forest & Woodland Formation,Formation,1.B.4,C
28,860237,860227,103,2.860237,1.B.5,F036,Accepted,Boreal Flooded & Swamp Forest,Boreal Flooded & Swamp Forest Formation,Boreal Flooded & Swamp Forest Formation,Boreal Flooded & Swamp Forest Formation,Formation,1.B.5,C
29,860246,860219,103,2.860246,2.A.1,F019,Accepted,"Tropical Lowland Grassland, Savanna & Shrubland","Tropical Lowland Grassland, Savanna & Shrubland Formation","Tropical Lowland Grassland, Savanna & Shrubland Formation","Tropical Lowland Grassland, Savanna & Shrubland Formation",Formation,2.A.1,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8386,686455,900033,47,2.686455,6.B.1.Na.2.b,CEGL002298,Accepted,Northern Tallgrass Quartzite - Granite Rock Outcrop,Quartzite - Granite Rock Outcrop Sparse Vegetation,Quartzite - Granite Rock Outcrop Sparse Vegetation,Quartzite - Granite Rock Outcrop Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Acidic Rock Outcrop AllianceQuartzite - Granite Rock Outcrop Sparse Vegetation",C
8387,684091,900032,47,2.684091,6.B.1.Na.2.b,CEGL005257,Accepted,Great Plains Dry Sandstone Cliff,Sandstone Great Plains Dry Cliff Sparse Vegetation,Sandstone Great Plains Dry Cliff Sparse Vegetation,Sandstone Great Plains Dry Cliff Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Acidic Cliff AllianceSandstone Great Plains Dry Cliff Sparse Vegetation",C
8388,684088,900031,47,2.684088,6.B.1.Na.2.b,CEGL002046,Accepted,Great Plains Xeric Limestone - Dolostone Cliff,Limestone - Dolostone Great Plains Xeric Cliff Sparse Vegetation,Limestone - Dolostone Great Plains Xeric Cliff Sparse Vegetation,Limestone - Dolostone Great Plains Xeric Cliff Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Alkaline Cliff AllianceLimestone - Dolostone Great Plains Xeric Cliff Sparse Vegetation",C
8389,689795,900032,47,2.689795,6.B.1.Na.2.b,CEGL002297,Accepted,Great Plains Sandstone Butte,Sandstone Butte Sparse Vegetation,Sandstone Butte Sparse Vegetation,Sandstone Butte Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Acidic Cliff AllianceSandstone Butte Sparse Vegetation",C
8390,687950,900032,47,2.687950,6.B.1.Na.2.b,CEGL002290,Accepted,Great Plains Xeric Sandstone Butte - Bluff,Sandstone Great Plains Xeric Butte - Bluff Sparse Vegetation,Sandstone Great Plains Xeric Butte - Bluff Sparse Vegetation,Sandstone Great Plains Xeric Butte - Bluff Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Acidic Cliff AllianceSandstone Great Plains Xeric Butte - Bluff Sparse Vegetation",C
8391,689335,900033,47,2.689335,6.B.1.Na.2.b,CEGL005261,Accepted,Redbeds Rock Outcrop,"Redbeds (Siltstone, Sandstone, Gypsum) Sparse Vegetation","Redbeds (Siltstone, Sandstone, Gypsum) Sparse Vegetation","Redbeds (Siltstone, Sandstone, Gypsum) Sparse Vegetation",Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Acidic Rock Outcrop AllianceRedbeds (Siltstone, Sandstone, Gypsum) Sparse Vegetation",C
8392,687645,900031,47,2.687645,6.B.1.Na.2.b,CEGL002296,Accepted,Great Plains Limestone Butte,Limestone Butte Sparse Vegetation,Limestone Butte Sparse Vegetation,Limestone Butte Sparse Vegetation,Association,"6.B.1.Na.2.bGreat Plains Cliff, Scree & Rock VegetationGreat Plains Cliff, Scree & Rock VegetationGreat Plains Alkaline Cliff AllianceLimestone Butte Sparse Vegetation",C
8393,685882,900029,47,2.685882,6.B.1.Na.3.a,CEGL001367,Accepted,NaN,Sarcobatus vermiculatus / Pseudoroegneria spicata Shrubland,<i>Sarcobatus vermiculatus / Pseudoroegneria spicata</i> Shrubland,Greasewood / Bluebunch Wheatgrass Shrubland,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationSarcobatus vermiculatus Great Plains Badlands AllianceSarcobatus vermiculatus / Pseudoroegneria spicata Shrubland,C
8394,683377,899181,47,2.683377,6.B.1.Na.3.a,CEGL001521,Accepted,NaN,Artemisia longifolia - Calamovilfa longifolia Sparse Vegetation,<i>Artemisia longifolia - Calamovilfa longifolia</i> Sparse Vegetation,Longleaf Wormwood - Prairie Sandreed Sparse Vegetation,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationArtemisia longifolia Badlands AllianceArtemisia longifolia - Calamovilfa longifolia Sparse Vegetation,C
8395,689825,899159,47,2.689825,6.B.1.Na.3.a,CEGL001951,Accepted,NaN,Arenaria hookeri Barrens Vegetation,<i>Arenaria hookeri</i> Barrens Vegetation,Hooker's Sandwort Barrens Vegetation,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationArenaria hookeri Rock AllianceArenaria hookeri Barrens Vegetation,C
8396,688291,899181,47,2.688291,6.B.1.Na.3.a,CEGL002195,Accepted,Longleaf Wormwood Badlands,Artemisia longifolia Badlands Sparse Vegetation,<i>Artemisia longifolia</i> Badlands Sparse Vegetation,Longleaf Wormwood Badlands Sparse Vegetation,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationArtemisia longifolia Badlands AllianceArtemisia longifolia Badlands Sparse Vegetation,C
8397,687090,900030,47,2.687090,6.B.1.Na.3.a,CEGL002050,Accepted,Great Plains Eroding Badlands,Eroding Great Plains Badlands Sparse Vegetation,Eroding Great Plains Badlands Sparse Vegetation,Eroding Great Plains Badlands Sparse Vegetation,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationEriogonum pauciflorum - Gutierrezia sarothrae Badlands AllianceEroding Great Plains Badlands Sparse Vegetation,C
8398,687410,900030,47,2.687410,6.B.1.Na.3.a,CEGL005270,Accepted,Wild Buckwheat - Snakeweed Badlands,Eriogonum pauciflorum - Gutierrezia sarothrae Badlands Sparse Vegetation,<i>Eriogonum pauciflorum - Gutierrezia sarothrae</i> Badlands Sparse Vegetation,Few-flower Buckwheat - Broom Snakeweed Badlands Sparse Vegetation,Association,6.B.1.Na.3.aGreat Plains Badlands VegetationGreat Plains Badlands VegetationEriogonum pauciflorum - Gutierrezia sarothrae Badlands AllianceEriogonum pauciflorum - Gutierrezia sarothrae Badlands Sparse Vegetation,C
8399,788799,899837,47,2.788799,6.B.1.Nb.1.a,CEGL002886,Accepted,NaN,Eriogonum fasciculatum / Selaginella bigelovii Sparse Vegetation,<i>Eriogonum fasciculatum</i> / <i>Selaginella bigelovii</i> Sparse Vegetation,Eastern Mojave Buckwheat / Bushy Spikemoss Sparse Vegetation,Association,"6.B.1.Nb.1.aWestern North American Cliff, Scree & Rock VegetationCalifornian Cliff, Scree & Rock VegetationSelaginella bigelovii Rock AllianceEriogonum fasciculatum / Selaginella bigelovii Sparse Vegetation",C
8400,685684,899794,47,2.685684,6.B.1.Nb.1.b,CEGL002295,Accepted,Black Hills Granite - Metamorphic Rock Outcrop,Granite - Metamorphic Black Hills Rock Outcrop Sparse Vegetation,Granite - Metamorphic Black Hills Rock Outcrop Sparse Vegetation,Granite - Metamorphic Black Hills Rock Outcrop Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationBlack Hills Cliff, Scree & Rock AllianceGranite - Metamorphic Black Hills Rock Outcrop Sparse Vegetation",C
8401,685709,899792,47,2.685709,6.B.1.Nb.1.b,CEGL001878,Accepted,NaN,Claytonia megarhiza Rock Vegetation,<i>Claytonia megarhiza</i> Rock Vegetation,Alpine Springbeauty Rock Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceClaytonia megarhiza Rock Vegetation",C
8402,934888,934875,47,2.934888,6.B.1.Nb.1.b,CEGL005509,Accepted,Rocky Mountain-Great Basin Wet Cliff & Spray Zone,Sullivantia hapemanii - Mimulus spp. Wet Rock Vegetation,<i>Sullivantia hapemanii - Mimulus</i> spp. Wet Rock Vegetation,Hapeman's Coolwort - Monkeyflower species Wet Rock Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationSullivantia hapemanii - Mimulus spp. Wet Rock AllianceSullivantia hapemanii - Mimulus spp. Wet Rock Vegetation",C
8403,857940,899792,47,2.857940,6.B.1.Nb.1.b,CEGL009605,Accepted,NaN,Petrophyton caespitosum Sparse Vegetation,<i>Petrophyton caespitosum</i> Sparse Vegetation,Tufted Rockmat Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AlliancePetrophyton caespitosum Sparse Vegetation",C
8404,785183,899792,47,2.785183,6.B.1.Nb.1.b,CEGL002801,Accepted,NaN,Holodiscus dumosus Rock Outcrop Sparse Vegetation,<i>Holodiscus dumosus</i> Rock Outcrop Sparse Vegetation,Rockspirea Rock Outcrop Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceHolodiscus dumosus Rock Outcrop Sparse Vegetation",C
8405,728744,899793,47,2.728744,6.B.1.Nb.1.b,CEGL005901,Accepted,NaN,Phacelia hastata - (Penstemon ellipticus) Sparse Vegetation,<i>Phacelia hastata - (Penstemon ellipticus</i>) Sparse Vegetation,Silverleaf Phacelia - (Rocky Ledge Penstemon) Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAquilegia flavescens - Phacelia hastata Cliff, Scree & Rock AlliancePhacelia hastata - (Penstemon ellipticus) Sparse Vegetation",C
8406,728737,899793,47,2.728737,6.B.1.Nb.1.b,CEGL005899,Accepted,NaN,Aquilegia flavescens - Senecio megacephalus Sparse Vegetation,<i>Aquilegia flavescens - Senecio megacephalus</i> Sparse Vegetation,Yellow Columbine - Rocky Ragwort Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAquilegia flavescens - Phacelia hastata Cliff, Scree & Rock AllianceAquilegia flavescens - Senecio megacephalus Sparse Vegetation",C
8407,685723,899792,47,2.685723,6.B.1.Nb.1.b,CEGL001948,Accepted,NaN,Aletes anisatus - Scutellaria brittonii Scree Vegetation,<i>Aletes anisatus - Scutellaria brittonii</i> Scree Vegetation,Rocky Mountain Indian-parsley - Britton's Skullcap Scree Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceAletes anisatus - Scutellaria brittonii Scree Vegetation",C
8408,683065,899792,47,2.683065,6.B.1.Nb.1.b,CEGL001971,Accepted,NaN,Heuchera bracteata - Heuchera parvifolia var. nivalis Rock Vegetation,<i>Heuchera bracteata - Heuchera parvifolia var. nivalis</i> Rock Vegetation,Rocky Mountain Alumroot - Littleleaf Alumroot Rock Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceHeuchera bracteata - Heuchera parvifolia var. nivalis Rock Vegeta",C
8409,685163,899792,47,2.685163,6.B.1.Nb.1.b,CEGL001938,Accepted,NaN,Aquilegia caerulea - Cirsium scopulorum Scree Sparse Vegetation,<i>Aquilegia caerulea - Cirsium scopulorum</i> Scree Sparse Vegetation,Colorado Blue Columbine - Mountain Thistle Scree Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceAquilegia caerulea - Cirsium scopulorum Scree Sparse Vegetation",C
8410,684445,899794,47,2.684445,6.B.1.Nb.1.b,CEGL005283,Accepted,Black Hills Igneous - Metamorphic Butte,Igneous - Metamorphic Black Hills Butte Sparse Vegetation,Igneous - Metamorphic Black Hills Butte Sparse Vegetation,Igneous - Metamorphic Black Hills Butte Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationBlack Hills Cliff, Scree & Rock AllianceIgneous - Metamorphic Black Hills Butte Sparse Vegetation",C
8411,689796,899794,47,2.689796,6.B.1.Nb.1.b,CEGL002307,Accepted,Black Hills Scree - Talus,Scree - Talus Black Hills Sparse Vegetation,Scree - Talus Black Hills Sparse Vegetation,Scree - Talus Black Hills Sparse Vegetation,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationBlack Hills Cliff, Scree & Rock AllianceScree - Talus Black Hills Sparse Vegetation",C
8412,687301,899792,47,2.687301,6.B.1.Nb.1.b,CEGL001134,Accepted,NaN,Rubus idaeus Scree Shrubland,<i>Rubus idaeus</i> Scree Shrubland,American Red Raspberry Scree Shrubland,Association,"6.B.1.Nb.1.bWestern North American Cliff, Scree & Rock VegetationRocky Mountain Cliff, Scree & Rock VegetationAletes anisatus - Holodiscus dumosus - Rubus idaeus Cliff, Scree & Rock AllianceRubus idaeus Scree Shrubland",C

In [42]:
unitDescriptions = pd.read_csv("USNVC_DownloadMarch2017/unitDescription.txt", sep='\t', encoding = "ISO-8859-1", dtype={"element_global_id":str})
print (unitDescriptions.dtypes)
display (unitDescriptions)

element_global_id            object
typeconceptsentence          object
parentkey                    object
parentname                   object
typeconcept                  object
diagnosticcharacteristics    object
rationale                    object
classificationcomments       object
similarnvctypescomments      object
physiognomy                  object
floristics                   object
plotcount                    float64
dynamics                     object
environment                  object
range                        object
nations                      object
subnations                   object
tncecoregions                object
usfsecoregions1994           object
usfsecoregions2007           object
omernikecoregions            object
federallands                 object
spatialpattern               object
plotsummary                  object
plottypal                    object
plotarchived                 object
plotconsistency              object
plotsize                     object
plotmethods                  object
classif_confidence_id        float64
confidencecomments           object
grank                        object
grankreviewdate              object
grankauthor                  object
grankreasons                 object
othercomments                object
lineage                      object
synonymy                     object
primaryconceptsource         object
descriptionauthor            object
acknowledgements             object
versiondate                  object
dtype: object

,element_global_id,typeconceptsentence,parentkey,parentname,typeconcept,diagnosticcharacteristics,rationale,classificationcomments,similarnvctypescomments,physiognomy,...,grankreviewdate,grankauthor,grankreasons,othercomments,lineage,synonymy,primaryconceptsource,descriptionauthor,acknowledgements,versiondate
0,683283,NaN,A3478,<i>Dasiphora fruticosa ssp. floribunda - Myrica gale - Trichophorum alpinum</i> Alkaline Shrub Fen Alliance,"This extremely rich boreal shrub fen community is found in the northern Great Lakes region of the United States and Canada, and probably elsewhere in central Canada. Stands occur in water tracks of large peatlands. Water pH is slightly acidic to circumneutral (5.8-7.8). Shrubs dominate the stand, covering at least 25% of the area. Dominants include <i>Betula pumila, Dasiphora fruticosa ssp. floribunda (= Pentaphylloides floribunda), Salix</i> spp. (including <i>Salix pedicellaris</i>). Scrubby forms of the tree species <i>Thuja occidentalis</i> and <i>Larix laricina</i> often occur with the shrubs on the hummocks. Other shrubs and dwarf-shrubs include <i>Andromeda polifolia, Chamaedaphne calyculata, Vaccinium oxycoccos</i> and others. The herbaceous layer is dominated by <i>Carex lasiocarpa, Carex buxbaumii, Carex livida</i>, and <i>Calamagrostis stricta</i>. Other graminoids include <i>Trichophorum alpinum (= Scirpus hudsonianus), Carex interior</i> and <i>Carex limosa</i>.",NaN,NaN,"Localized areas of somewhat calcium-rich groundwater are placed into ~<i>Carex lasiocarpa - Trichophorum caespitosum - Rhynchospora capillacea / Andromeda polifolia</i> Fen (CEGL002496)$$. The ~Northern Patterned Rich Fen Complex (CECX005707)$$ includes both this rich shrub fen and the boreal rich graminoid fen, ~<i>Carex lasiocarpa - Carex buxbaumii - Trichophorum caespitosum</i> Boreal Fen (CEGL002500)$$, in a string (hummock) and flark (hollow) pattern [see Harris et al. (1996)]. This type may occur in Michigan, but further verification is needed before listing it (D. Albert, P. Comer pers. comm.). In fact, in Michigan, it may be very similar to the Great Lakes Shrubby-cinquefoil - Sweet Gale Rich Shore Fen type, ~<i>Dasiphora fruticosa ssp. floribunda - Myrica gale</i> Shore Fen (CEGL005275)$$.",NaN,NaN,...,3/24/2000,NaN,"This type is uncommon in the United States, but its status in Canada should be determined before refining the rank.",NaN,NaN,"<b>?</b> Extremely rich fen: ericaceous shrub / sedge / brown moss (W17) (Harris et al. 1996) [This is a patterned rich fen that may describe both this type and rich graminoid fen, ~<i>Carex lasiocarpa - Carex buxbaumii - Trichophorum caespitosum</i> Boreal Herbaceous Vegetation (CEGL002500)$. It may also include the boreal calcareous seepage fen, ~<i>Carex lasiocarpa - Trichophorum caespitosum - Rhynchospora capillacea / Andromeda polifolia</i> Herbaceous Vegetation (CEGL002496)$$.] <br><b>></b> Fen Birch Organic Thicket Swamp Type (Lee et al. 1998)<br><b>></b> Low White Cedar Shrub Fen Type (Lee et al. 1998)<br><b>=</b> Strings (Glaser 1992b)<br><b>></b> Tamarack - White Cedar Coniferous Treed Fen Type (Lee et al. 1998)",D. Faber-Langendoen,D. Faber-Langendoen,NaN,12/19/1998
1,683284,NaN,A2036,<i>Populus tremuloides</i> Rocky Mountain Forest &amp; Woodland Alliance,NaN,NaN,NaN,Stands in this association may have been altered by grazing.,NaN,NaN,...,2/23/1994,NaN,NaN,NaN,NaN,<b>=</b> <i>Populus tremuloides / Symphoricarpos oreophilus / Bromus carinatus</i> Community Type (Mueggler 1988)<br><b>=</b> <i>Populus tremuloides/Symphoricarpos oreophilus/Bromus carinatus</i> (Bourgeron and Engelking 1994)<br><b><</b> DRISCOLL FORMATION CODE:I.B.3.b. (Driscoll et al. 1984),Western Ecology Group,NaN,NaN,NaN
2,683289,NaN,A3412,<i>Juncus effusus - Andropogon glomeratus var. pumilus - Saccharum giganteum</i> Ruderal Marsh Alliance,"Stands of this vegetation type result from hydrological alteration of wet muhly prairies in the south Florida Everglades. Regional and local drainage of sites with this association results in succession to a substantially different community, which now covers extensive areas. <i>Andropogon glomeratus var. pumilus</i> and <i>Saccharum giganteum</i> are important species, along with persistent <i>Muhlenbergia filipes</i>. Scattered woody species are also present, including both native (<i>Morella cerifera (= Myrica cerifera), Metopium toxiferum, Ilex cassine, Persea palustris</i>, and <i>Baccharis halimifolia</i>) and alien (<i>Melaleuca quinquenervia, Schinus terebinthifolius</i>, and <i>Casuarina equisetifolia</i>) species.",NaN,NaN,"Nomenclatural notes on <i>Muhlenbergia</i> (C. Nordman/M. Pyne 10-07): NatureServe Ecology varies from Kartesz (1999) on the nomenclature of three related southeastern <i>Muhlenbergia</i> taxa. The names in Kartesz (1999) for these plants are <i>Muhlenbergia capillaris</i> (Lam.) Trin. var. <i>capillaris</i>; <i>Muhlenbergia capillaris</i> (Lam.) Trin. var. <i>filipes</i> (M.A. Curtis) Chapman ex Beal; and <i>Muhlenbergia capillaris</i> (Lam.) Trin. var. <i>trichopodes</i> (Ell.) Vasey. We have chosen to treat all three of these at the specific level, as (respectively) <i>Muhlenbergia capillaris</i> Lam.; <i>Muhlenbergia filipes</i> M.A. Curtis; and <i>Muhlenbergia expansa</i> (Poir.) Trin. A more recent innovation, which we will adopt at some point, is the recent recognition that <i>Muhlenbergia sericea</i> (Michx.) P.M. Peterson is the correct name (based on nomenclatural priority) for the plant formerly known as <i>Muhlenbergia filipes</i> M.A. Curtis (= <i>Muhlenbergia capillaris var. filipes</i>) (Gustafson and Peterson 2007).",NaN,NaN,...,6/23/1997,NaN,NaN,NaN,NaN,<b>=</b> Muhly-beard grass prairie on marl (Hilsenbeck et al. 1979),A.S. Weakley,A.S. Weakley,NaN,2/1/1996
3,683291,NaN,A4013,<i>Spartina alterniflora - Spartina cynosuroides</i> Brackish Tidal Marsh Alliance,"This association occurs on fresh to brackish, mid-tidal, sandy/gravelly rivershores along the north and mid-Atlantic Coast. It occurs in low areas where there is a longer duration of flooding. Wave and ice scour can have a significant influence on the year-to-year appearance of the vegetation, which tends to be sparse. This vegetation often occurs in nearly pure stands of <i>Schoenoplectus pungens (= Scirpus pungens)</i> but can be intermixed with <i>Spartina alterniflora</i> or <i>Spartina cynosuroides</i> in more brackish areas. Species diversity tends to be low due to winter storm scour, but associates can include <i>Amaranthus cannabinus, Polygonum punctatum, Cyperus bipartitus (= Cyperus rivularis)</i>, and <i>Bidens</i> spp. <i>Sagittaria graminea, Sagittaria latifolia, Eleocharis palustris (= Eleocharis smallii), Gratiola virginiana, Elatine americana, Isoetes riparia</i>, and <i>Cyperus bipartitus</i> can occur, but are absent in the northern part of the range. As the salinity decreases <i>Zizania aquatica</i> can also be an associate.",NaN,NaN,The nominal species has long been known as <i>Scirpus americanus</i>.,NaN,NaN,...,12/1/1997,NaN,NaN,NaN,NaN,<b>=</b> <i>Schoenoplectus pungens</i> Tidal Herbaceous Vegetation (Fleming et al. 2007b)<br><b>=</b> <i>Scirpus pungens</i> Herbaceous Vegetation (Bartgis 1986)<br><b>?</b> <i>Scirpus</i> marsh community (brackish mid-tidal marsh border) (Barrett 1989)<br><b>?</b> Brackish Tidal Marsh (Rawinski 1984a) [formerly Southern New England and Gulf of Maine.],"Eastern Ecology Group, mod. S.L. Neid",S.L. Neid and G.P. Fleming,NaN,5/24/2007
4,683293,NaN,A3613,<i>Tsuga heterophylla - Thuja plicata</i> Warm-Mesic Central Rocky Mountain Forest &amp; Woodland Alliance,"This small-patch, hygric (damp) to hydric (wet) community is associated with the inland penetration of a Pacific maritime climatic regime, occurring in the east Cascades and northeastern Washington, east into northern Idaho and northwestern Montana. This type ranges in elevation from 460 to 1430 m (1500-4700 feet). The primary environmental driver is abundant water throughout the growing season; standing water is often present early in the growing season, and water tables are high throughout the year. This is typically a streamside stringer, around seeps, where toeslopes intercept the water table, and some of the most extensive examples are associated with gentle slopes (&lt;20 % inclination) with perched water tables. The stands are often sheltered in valley bottoms. Sites often have considerable microsite variation due to hummocking, and this can be reflected in the within-stand vegetation patterning. Soils are derived primarily from alluvium of various geologic origins. With textures ranging from loamy sands to silt loams and often having an appreciable gravel content, soils are very permeable. The tree canopy is highly variable in cover with dense old-growth <i>Thuja</i>-dominated stands approaching 100% canopy cover and other sites that perhaps have experienced wind throw having less than 50% cover. <i>Thuja plicata</i> dominates both the upper canopy and the reproductive layers; <i>Tsuga heterophylla, Abies grandis</i> and <i>Picea engelmannii</i> are consistent upper canopy components; only <i>Tsuga</i> has appreciable cover in the reproductive layers. In a modal expression of the type a nearly continuous layer of <i>Athyrium filix-femina</i> dominates the undergrowth, concealing a rich diversity of forbs. Some sites have appreciable cover of tall shrubs including <i>Taxus brevifolia, Alnus viridis ssp. sinuata</i>, and <i>Acer glabrum</i>. Incidental individuals or small patches of <i>Oplopanax horridus</i> may be found. The short and dwarf-shrub layers are relatively inconspicuous, a combined cover seldom exceeding 10%. Some consistently present hygric- to hydric-indicating forbs include <i>Senecio triangularis, Trautvetteria caroliniensis, Streptopus amplexifolius, Gymnocarpium dryopteris, Viola glabella, Aconitum columbianum</i>, and <i>Circaea alpina</i>; some have considered the presence of the first four of these forbs to be indicative of the type when the cover of <i>Athyrium</i> is less than 1%.",NaN,NaN,"It has been the approach of Inland Northwest U.S. vegetation scientists to consider stands with a mix of <i>Thuja plicata</i> and <i>Tsuga heterophylla</i> (and <i>Abies grandis</i>) or either species alone and occurring on sites sufficiently wet to support at least 5% <i>Oplopanax horridus</i> or <i>Athyrium filix-femina</i> to be classed as <i>Thuja plicata</i> habitat types or plant associations. Daubenmire and Daubenmire (1968) argued, based on their investigations in northern Idaho and eastern Washington, that even where <i>Tsuga</i> constitutes the dominant tree species in a stand, it would not so remain. Ultimately the nurse-logs, from which these trees generated and grew, would decay, favoring <i>Thuja</i> reproduction in these wet environments (<i>Tsuga</i> not establishing well on mineral substrates). The Daubenmires also noted that, if <i>Tsuga / Athyrium</i> or <i>Tsuga / Oplopanax</i> segregates were recognized, they would include few stands and little area; they also demonstrated that there was no floristic differences in the undergrowth between <i>Thuja</i>- and <i>Tsuga</i>-dominated stands. Others have followed suit (Pfister et al. 1977, Lillybridge et al. 1995, Williams et al. 1995) and have included, even as did the Daubenmires, stands from wet environments and having <i>Tsuga</i> and no <i>Thuja</i> within the <i>Thuja</i> series (alliance).<br /><br />The classification effort underway in Waterton-Glacier International Peace Park (IPP) has chosen to follow the USNVC and its predilection for recognizing actual cover rather than potential. The IPP classification distinguishes <i>Tsuga</i> types when the cover of this species is at least 25% of the upper canopy; the 25% figure is rather arbitrary and corresponds to no intrinsic break in the cover of either tree species. Another problematical distinction is that between the relative indicator values of <i>Oplopanax</i> and <i>Athyrium</i>; some consider these two species to be indicator equivalents (Lillybridge et al. 1995), whereas others (Hansen et al. 1995) are unequivocal in stating that <i>Oplopanax</i> is characteristic of wetter environments. Where the distribution of <i>Athyrium</i> and <i>Oplopanax</i> overlap, from the Clearwater River northward in Idaho, <i>~Thuja plicata / Athyrium filix-femina</i> Forest (CEGL000473)$$ is considerably more uncommon, these sites being occupied by <i>~Thuja plicata - Tsuga heterophylla / Oplopanax horridus</i> Rocky Mountain Swamp Forest (CEGL000479)$$ in which <i>Athyrium</i> is 100% constant and its cover frequently exceeds that of <i>Oplopanax</i>. One cannot invoke cold-air drainage and ponding on the latter type (noted by Hansen et al. 1995) as the distinguishing factor because <i>Athyrium</i> is abundantly represented on all <i>Oplopanax</i> sites. At least in northern Idaho <i>Oplopanax</i> sites occurred on coarser-textured soils with greater amounts of gravel (40-60%).",NaN,NaN,...,2/1/1996,NaN,NaN,NaN,NaN,"<b>=</b> <i>Thuja plicata / Athyrium filix-femina</i> Habitat Type (Daubenmire and Daubenmire 1968)<br><b>=</b> <i>Thuja plicata / Athyrium filix-femina</i> Habitat Type, <i>Athyrium filix-femina</i> Phase (Hansen et al. 1995)<br><b>=</b> <i>Thuja plicata / Athyrium filix-femina</i> Habitat Type, <i>Athyrium filix-femina</i> and <i>Adiantum pedatum</i> phases (Cooper et al. 1987)<br><b>><</b> <i>Thuja plicata / Oplopanax horridus</i> (Lillybridge et al. 1995) [THPL/OPHO ASSOCIATION CCS211] <br><b>><</b> <i>Thuja plicata / Oplopanax horridus</i> Plant Association (Williams et al. 1995)<br><b>=</b> <i>Thuja plicata/Athyrium filix-femina</i> (Bourgeron and Engelking 1994)<br><b><</b> DRISCOLL FORMATION CODE:I.A.9.c. (Driscoll et al. 1984)",Western Ecology Group,S.V. Cooper,NaN,4/15/2004
5,683294,NaN,A3397,<i>Rhynchospora</i> spp. - <i>Calamagrostis canadensis - Rhexia virginica</i> Coastal Plain Pondshore Marsh Alliance,"This wetland community of southern New England and the mid-Atlantic occurs on deep mucky soils of shallow depressions and is influenced by a long hydroperiod. Sedges and rushes are predominant, admixed with floating-leaved aquatics. No single species is dominant, but characteristically present are <i>Cladium mariscoides, Rhynchospora alba, Rhynchospora inundata, Xyris smalliana, Eleocharis equisetoides, Schoenoplectus pungens (= Scirpus pungens)</i>, and <i>Juncus canadensis</i>. <i>Nymphaea odorata</i> also occurs, particularly where water is deeper.",NaN,NaN,NaN,NaN,NaN,...,12/1/1997,NaN,NaN,NaN,NaN,<b>=</b> <i>Cladium mariscoides - Eleocharis equisetoides</i> Herbaceous Vegetation (Walz et al. 2006b),Eastern Ecology Group,S.L. Neid and L.A. Sneddon,NaN,6/26/2012
6,683297,NaN,A3613,<i>Tsuga heterophylla - Thuja plicata</i> Warm-Mesic Central Rocky Mountain Forest &amp; Woodland Alliance,"This plant association occurs within the Pacific maritime-influenced climatic regions of the northern Rocky Mountains in the northern Idaho Batholith and Bitterroot Mountains ecoregional sections, within the Clearwater River sub-basin of Idaho. The association occurs on warm, moist, gentle north- to east-facing slopes at 915-1525 m (3000-5000 feet) elevation. These highly productive sites often support rapidly growing, large-diameter <i>Abies grandis</i> and <i>Pseudotsuga menziesii</i>. Giant <i>Thuja plicata</i> are prominent in mid- to late-seral stands. The association is characterized by the abundance of <i>Taxus brevifolia</i> in the understory tall-shrub or low-tree canopy. <i>Paxistima myrsinites</i> and <i>Lonicera utahensis</i> are often present. Associated herbaceous species include <i>Anemone piperi, Asarum caudatum, Clintonia uniflora, Coptis occidentalis, Goodyera oblongifolia, Maianthemum stellatum (= Smilacina stellata), Tiarella trifoliata, Trillium ovatum</i>, and <i>Viola orbiculata</i>.",NaN,NaN,The association is classified by Cooper et al. (1987) as a phase of the <i>Thuja plicata / Asarum caudatum</i> plant association. Crawford and Johnson (1985) argue that these stands should be treated as an association (as it is here) rather than a phase of the broader association.,NaN,NaN,...,1/29/2001,NaN,"This regional endemic plant association is restricted to warm, moist, gentle north- to east-facing slopes within the Pacific maritime-influenced climatic region of the northern Rocky Mountains. More than 20 but less than 100 occurrences of 40 acres average size are estimated to be present within the approximately 3000 square mile range. The number and quality of stands has been adversely impacted directly by (and through cumulative effects of) road construction and timber harvest activities. The predominant landscape context of occurrences is intensively managed forest. Stands of the association continue to be threatened by timber harvest activities. Occurrences are increasingly subjected to invasion by exotic and noxious weed species. High-quality stands are clustered in inaccessible locations and within wilderness areas. Based on review of the number, size, and quality of occurrences the global rarity rank of the association is changed from G3 to G2.",NaN,NaN,<b>?</b> <i>Thuja plicata / Asarum caudatum</i> Habitat Type (Cooper et al. 1987)<br><b>=</b> <i>Thuja plicata/Taxus brevifolia/Asarum caudatum</i> (Bourgeron and Engelking 1994)<br><b><</b> DRISCOLL FORMATION CODE:I.A.9.c. (Driscoll et al. 1984),S.K. Rust,S.K. Rust,NaN,11/26/1997
7,683299,NaN,A3339,<i>Triadica sebifera - Melaleuca quinquenervia - Schinus terebinthifolius</i> Ruderal Flooded &amp; Swamp Forest Alliance,"This wetland forest type is broadly defined to cover a variety of sites strongly dominated by the exotic tree <i>Triadica sebifera (= Sapium sebiferum)</i> (Euphorbiaceae). Other wetland trees may be present, including <i>Acer rubrum var. drummondii, Salix nigra</i>, and <i>Salix caroliniana</i>. Various wetland grasses, sedges, and forbs are present.",NaN,NaN,NaN,NaN,NaN,...,11/22/1997,NaN,NaN,NaN,NaN,<b>=</b> <i>Sapium</i> dominated forest (Nijjer et al. 2007),A.S. Weakley 1-96,A.S. Weakley,NaN,10/20/2015
8,683300,NaN,A2108,<i>Pinus monophylla - Juniperus osteosperma</i> / Shrub Understory Woodland Alliance,This association has only been described from Zion National Park. Until further inventory is completed there is no global information.,NaN,NaN,NaN,NaN,NaN,...,8/14/2001,NaN,NaN,NaN,NaN,<b>=</b> <i>Pinus monophylla-(Juniperus osteosperma) / Quercus turbinella</i> Association (Evens et al. 2014),Western Ecology Group,Western Ecology Group,NaN,1/6/2017

In looking at the data, we seem to have several attributes that might be usable unique identifiers - element_global_id, elementuid, and databasecode. There are a few ways to test whether these are unique in the whole dataset, but I found one of the easiest things to do was get the size (shape) of the whole dataframe and then check unique size of the attributes (columns) in question. From this, it looks like any one of these is unique in the dataset, and I'm really not sure what the attributes mean and what their significance is. From other experience with NatureServe's data systems, it seems like the "Element Global ID" might be the unique ID to reference, but it's not clear whether or not it is persistent over time. Looking at the obsolete records might give us some clues as to how they handle things. We may opt to use our own assigned persistent ID depending on how we want to ultimately handle versioning of the records over time or our own way of dealing with deprecation.

In [5]:
print (units.shape)
print (units.element_global_id.unique().size)
print (units.elementuid.unique().size)
print (units.databasecode.unique().size)

(8416, 14)
8416
8416
8416

In exploring the ID issue a little further, I was curious about element_global_id and its persistence. This attribute appears to be the main identifier in the two tables containing information about obsolete entities. So, now I want to know if those presumably obsolete IDs show up back in the "live" units tables (at this point, I assume that unit.txt and unitDescription.txt basically have the same core unique identifiers. This is maybe a dumb way to do this test, but I read in the element_global_id values from all three tables throw unique values into arrays and then compare the arrays to see if there are any duplicates with unit.txt, where I expect to only find unique (and perhaps persistent element_global_id values).

In [6]:
obsoleteUnits = pd.read_csv("USNVC_DownloadMarch2017/UnitObsoleteName.txt", sep='\t', encoding = "ISO-8859-1", usecols=[0])
obsoleteParents = pd.read_csv("USNVC_DownloadMarch2017/UnitObsoleteParent.txt", sep='\t', encoding = "ISO-8859-1", usecols=[0])
uniqueUnits = units.element_global_id.unique()
uniqueObsoleteUnits = obsoleteUnits.element_global_id.unique()
uniqueObsoleteParents = obsoleteParents.element_global_id.unique()
print (any((uniqueUnits == uniqueObsoleteUnits).all() for uniqueUnits in uniqueObsoleteUnits))
print (any((uniqueUnits == uniqueObsoleteParents).all() for uniqueUnits in uniqueObsoleteParents))
print (any((uniqueObsoleteUnits == uniqueUnits).all() for uniqueObsoleteUnits in uniqueUnits))
print (any((uniqueObsoleteParents == uniqueUnits).all() for uniqueObsoleteParents in uniqueUnits))

False
False
False
False

I'm concluding (for the moment) that we should use element_global_id as a unique and persistent opaque identifier for a given unit in this data system over time. We still need to decide if we will adopt this as the core identifier for our purposes or assign our own for absolute certainty since we don't really know what all rules apply in the NatureServe Biotics system but suspect some level of squishiness given the multiple identifiers that seem to be in their data now. The "elementuid" is just a "2." with the element_global_id - don't know what that means, so maybe we can ignore it unless someone tells us something useful.

Both databasecode and classificationcode (don't understand the significance of the attribute names) have some part to play in establishing display titles for the units in the application. Certain databasecode values also appear in the one posted proceedings document from the ESA panel, where they seem to be used as meaningful shorthand (kind of a PITA, but as long as its consistent...). It appears that classificationcode is prefixed on Class, Subclass, Formation, and Division names and databasecode is prefixed on Macrogroup, Group, Alliance, and Association units to produce working full titles.

A different set of rules seems to apply for the Cultural units where the current app seems to be conflicting in terms of what is shown at a unit document level and what shows up in search results. Argh! We'll see if we can get a consistent ruleset nailed down that relates the identifiers to title and shorthand conventions so we better know how to package and present.

parent_id appears to be a reference to a parent element_global_id, establishing the hierarchy, though we need to be careful about number handling with Pandas so I explicitly made both those IDs strings on the way in.

Given what we've discovered so far, we probably have enough information to start laying out the unit data structure we want. Assuming we might make one overall pass at establishing initial records, at least, I build this into a list of documents. A few conventions I'm playing with here:

* Assign more human-friendly attribute names to the things that we will display to people, but retain a few of the "ugly names" for things that have special meaning in the data assembly process
* Build logical buckets of information into sub-documents, but don't go too crazy in deeply nesting the structure (at least for now as we're working with better understanding the data)

There appears to be some messiness in the values, so the cleanString function can be tweaked as we work through to fix problems.

In [62]:
def cleanString(text):
    replacements = {'&amp;': '&',"&lt;":"<","&gt;":">"}
    for x,y in replacements.items():
        text = text.replace(x, y)
    return (text)

In [67]:
import uuid

nvcsUnits = []
for index,row in units.iterrows():
    if index > 10:
        break
    unitDoc = {"_id":str(uuid.uuid4())}
    unitDoc["Identifiers"] = {}
    unitDoc["Identifiers"]["element_global_id"] = row["element_global_id"]
    unitDoc["Identifiers"]["Database Code"] = row["databasecode"]
    unitDoc["Identifiers"]["Classification Code"] = row["classificationcode"]
    
    unitDoc["Hierarchy"] = {}
    unitDoc["Hierarchy"]["parent_id"] = row["parent_id"]
    unitDoc["Hierarchy"]["Classification Level ID"] = row["d_classification_level_id"]
    unitDoc["Hierarchy"]["Hierarchy Level"] = row["hierarchylevel"]
    
    if row["hierarchylevel"] in ["Class","Subclass","Formation","Division"]:
        unitDoc["Identifiers"]["Display Title"] = row["classificationcode"]+" "+row["colloquialname"]+" "+row["hierarchylevel"]
    else:
        unitDoc["Identifiers"]["Display Title"] = row["databasecode"]+" "+row["colloquialname"]+" "+row["hierarchylevel"]
    
    thisUnitDescription = unitDescriptions.loc[unitDescriptions["element_global_id"] == row["element_global_id"]]

    unitDoc["Overview"] = {}
    unitDoc["Overview"]["Scientific Name"] = row["scientificname"]
    unitDoc["Overview"]["Colloquial Name"] = row["colloquialname"]
    unitDoc["Overview"]["Formatted Scientific Name"] = cleanString(row["formattedscientificname"])
    unitDoc["Overview"]["Translated Name"] = row["translatedname"]
    unitDoc["Overview"]["Type Concept Sentence"] = cleanString(thisUnitDescription["typeconceptsentence"].values[0])
    unitDoc["Overview"]["Type Concept"] = cleanString(thisUnitDescription["typeconcept"].values[0])
    unitDoc["Overview"]["Diagnostic Characteristics"] = thisUnitDescription["diagnosticcharacteristics"].values[0]
    unitDoc["Overview"]["Rationale"] = thisUnitDescription["rationale"].values[0]
    unitDoc["Overview"]["Classification Comments"] = cleanString(thisUnitDescription["classificationcomments"].values[0])

    unitDoc["Vegetation"] = {}
    unitDoc["Vegetation"]["Physiognomy and Structure"] = cleanString(thisUnitDescription["physiognomy"].values[0])
    
    nvcsUnits.append(unitDoc)
display (nvcsUnits)

[{'Hierarchy': {'Classification Level ID': 101,
   'Hierarchy Level': 'Class',
   'parent_id': nan},
  'Identifiers': {'Classification Code': '1',
   'Database Code': 'C01',
   'Display Title': '1 Forest & Woodland Class',
   'element_global_id': '860217'},
  'Overview': {'Classification Comments': 'Plantations, ruderal, and native forest and woodland stands are typically placed in this class. Some plantation forests can be placed here rather than in <i>7. ~Agricultural & Developed Vegetation Cultural Class (CCL01)$$</i> despite having a canopy layer that may be very regular (spaced in planted rows), if the tree regeneration, shrub and ground layers develop spontaneously with irregular horizontal spacing, similar to native forests (i.e., regular human intervention does not occur for these layers). However, where plantations have highly regular horizontal structure, with regular human intervention in all layers (e.g., through cutting, spraying, ground-layer mowing), they may better be placed in <i>7. ~Agricultural & Developed Vegetation Cultural Class (CCL01)$$</i>.<br /><br />Similarly, tree-dominated vegetation that has a natural, irregular horizontal spacing in the tree layer, but highly regular shrub or herb layers because of human intervention, should be placed in <i>7. ~Agricultural & Developed Vegetation Cultural Class (CCL01)$$</i>. For example, shade coffee, cacao, and other woody agricultural crops grown under native (or exotic) tree species and in which all non-treed strata layers are subject to regular human intervention should be placed in that class.<br /><br />Included in this class are low-statured trees that overtop other growth forms. These include tree sapling and seedling stands with trees <2 m, where the tree growth form is at least 10% cover and overtops other growth forms. These include subarctic woodlands and coastal dwarf-tree woodlands that are <2 m but are single-stemmed with definite crowns. Conversely, treed bogs and fens, with low stunted trees and conical canopies, and otherwise sharing the moss and dwarf-shrub layers of open bogs and fens, are placed with those types. Where trees share the same strata as grasslands and shrublands (e.g., tallgrass brush prairie of 1-3 m, with trees <2 m), the vegetation is placed in the shrub- and herb-dominated classes.<br /><br />Tree cover ranges from 10-100%, and is inclusive of what are called forests, woodlands, and tree savannas, at least in the non-tropical regions. The class limit of 10% tree cover (for mesomorphic tree growth forms) follows that of FAO\'s Global Forest Resources Assessment 2000 (FAO 2001). We exclude stands of trees planted primarily for agricultural production (such as fruit tree or forest plantations) and typically agroforestry, as well as those in developed lands, such as cities and roadsides (they are placed in Class 7, Formation 7.A.2). However, unlike FAO, we do not include what FAO calls "temporarily unstocked areas" (such as clearcuts, burnt areas) unless the tree growth form is actually present at 10% cover--even if in seedling or sapling form--and exceeds the height of other growth forms.<br /><br />Other classifications may limit forests and woodland to a narrower range of tree cover. For example, forests and woodlands are sometimes defined as 25-100% cover, and distinguished from tree savannas with 10-25% cover which are included under broadly defined grassland and shrubland classes (Driscoll et al. 1984, FGDC 1997, Grossman et al. 1998, Minnesota DNR 2005b). UNESCO (1973) required that tree savannas have a strong herbaceous layer (>50% graminoid cover). Still, a variety of definitions of tree savanna have been published, from the 10-25% cover noted above, to 10-30% cover in Nelson (2005), 10-40% in UNESCO (1973), and 10-50% cover in Curtis (1959). Blue oak, Engelmann oak, and other woodlands in California Mediterranean woodlands are typically between 10 and 60% cover, and California State ecologists place these in Forest & Woodland (Barbour et al. 2007). However, apart from tree savannas, there are many other forest and woodland types and regions where the degree of canopy closure plays less of a role in defining types, for example, forested swamps and bogs, longleaf pine woodlands (Peet 2006), eastern pine barrens, and subarctic woodlands.<br /><br />Thus, given the variety of situations, we have chosen a more inclusive definition of forest and woodland that encompasses most tree savanna concepts, and rely on lower levels of the hierarchy to make distinctions based on a combination of biogeography, ecology, and floristics. For example, in the context of the eastern Great Plains tallgrass prairie-forest border, it is common to recognize oak savannas, based on open tree cover levels (e.g., 5-30% tree cover in Nelson 2005), as separate from oak woodlands (30-80% cover) and oak forests (80-100% cover). Savannas may be distinguished from forests or woodlands, but these structural distinctions often correspond to lower-level units of the NVC hierarchy (e.g., group, alliance, and association). Still, Dixon et al. (2014) and others suggest that there may be good ecological reasons to treat upland tropical tree savannas, with 10-40% tree cover, trees <8 m tall, and a substantial graminoid layer as part of <i>2. ~Shrub & Herb Vegetation Class (C02)$$</i>, and we allow for that option here.',
   'Colloquial Name': 'Forest & Woodland',
   'Diagnostic Characteristics': 'Mesomorphic <i>tree</i> growth forms (<i>broad-leaved, needle-leaved</i>, and <i>sclerophyllous trees, palms, bamboo trees</i>, and <i>tree ferns</i>) have &gt;10% canopy cover, a spontaneous, irregular horizontal canopy spacing, and overtop other growth forms, except in tropical upland regions, where trees typically have &gt;40% cover, are &gt;8 m tall, and the vegetation lacks a substantial graminoid layer.',
   'Formatted Scientific Name': 'Mesomorphic Tree Vegetation Class',
   'Rationale': nan,
   'Scientific Name': 'Mesomorphic Tree Vegetation Class',
   'Translated Name': 'Mesomorphic Tree Vegetation Class',
   'Type Concept': '<i>Trees</i> with broadly mesomorphic (including scleromorphic) growth forms (including <i>broad-leaved, needle-leaved, sclerophyllous, palm</i>, and <i>bamboo trees</i>, and <i>tree ferns</i>) characterize this type. Vegetation structure typically has irregular horizontal spacing. The mesomorphic tree canopy is typically >10% cover and often exceeds 5 m in height, and often has both a mature (overstory) and regeneration layer, except in tropical upland savanna regions, where trees typically have >40% cover, are >8 m tall, and the vegetation lacks a substantial graminoid layer. Climates range from humid tropical to boreal and subalpine, with fairly moderate moisture and temperature conditions. Substrate moisture conditions vary from dry to wet. Vegetation includes tropical, temperate, and boreal forests and woodlands.',
   'Type Concept Sentence': 'Tropical, temperate and boreal forests, woodlands and tree savannas characterized by broadly mesomorphic (including scleromorphic) tree growth forms (including <i>broad-leaved, needle-leaved, sclerophyllous, palm, bamboo trees</i>, and <i>tree ferns</i>), typically with at least 10% cover (but tropical tree savannas up to 40% cover, when trees <8 m tall), irregular horizontal spacing of vegetation structure, and spanning humid to seasonally dry tropical to boreal and subalpine climates and wet to dry substrate conditions. Includes native forests, as well as managed, and some plantation forests where human management is infrequent.'},
  'Vegetation': {'Physiognomy and Structure': '<i>Growth Forms</i>: Stands are dominated by mesomorphic trees, including <i>broad-leaved deciduous</i> (including mostly deciduous, winter-deciduous, facultatively-deciduous), <i>broad-leaved evergreen</i> (including mostly evergreen), <i>needle-leaved</i> (deciduous and evergreen), <i>sclerophyllous trees, palms, bamboo trees</i>, and <i>tree ferns</i>. Tree growth forms generally have a single main stem and more-or-less definite crowns, and may be as low as 2 m (scrub trees) (e.g., tropical cloud elfin forest, mesquite woodland). Where growth forms are not easily defined, woody plants equal to or >5 m at maturity are considered trees (FGDC 2008).<br /><br /><i>Structure</i>: Typical stands have one or more of the tree growth forms exceeding 5 m in height, and the canopy has irregular horizontal tree stem spacing, with a minimum of 10% canopy cover (8 m in height and minimum of 40% in tropical forests and woodlands, as low as 2 m in subarctic woodlands). A tree regeneration layer is often present, along with various associated growth forms (shrubs, herbs, nonvasculars). Stands of trees where the tree growth form is short (<5 m) in height but overtopping shrub and herb growth forms, may also be placed in this class.'},
  '_id': '67c1beba-14da-4dce-ac32-256525ba70fa'},
 {'Hierarchy': {'Classification Level ID': 101,
   'Hierarchy Level': 'Class',
   'parent_id': nan},
  'Identifiers': {'Classification Code': '2',
   'Database Code': 'C02',
   'Display Title': '2 Shrub & Herb Vegetation Class',
   'element_global_id': '860211'},
  'Overview': {'Classification Comments': 'This class includes both non-treed grasslands and shrublands, and open tree savannas, where tree canopy cover is typically <10%. Non-tropical tree savannas, defined by a strong graminoid layer (>50% in UNESCO 1973) and some level of open tree cover (10-25% cover in UNESCO (1973), 10-30% cover in Nelson (2005), 10-50% cover in Curtis (1959)), often closely resemble open upland grasslands and shrublands, especially in grassland regions. Thus, in this particular realm of vegetation, the open tree canopy, in combination with the ground layer, helps define savanna vegetation, distinct from forests or woodlands (e.g., Nelson 2005). But in many other regions and vegetation types (e.g., forested swamps and bogs, longleaf pine woodlands (Peet 2006), California oak woodlands (Barbour et al. 2007), subarctic woodlands), the role of canopy closure varies. Thus, in non-tropical regions, we generally place tree savannas, where trees >5 m have >10% cover, with woodland and forest. However, as Dixon et al. (2014) and others suggest, there may be good ecological reasons to treat upland tropical tree savannas, with up to 40% tree cover, trees <8 m tall, and a substantial graminoid layer, as part of <i>2. ~Shrub & Herb Vegetation Class (C02)$$</i>, and we allow for that option here.<br /><br />Croplands with a spontaneous ground layer of "weeds," where the annual rotation of crops prevents a persistent ground layer of herbs, are treated in <i>7. ~Agricultural & Developed Vegetation Cultural Class (CCL01)$$</i>. If agricultural practices are abandoned, these sites may succeed to more persistent "ruderal" grasslands and shrublands (and forests) and would be placed in this class.<br /><br />Where grasses and shrubs overtop low trees ("brush prairie"), the stands are placed here in Shrub & Herb Vegetation. These situations may often occur in grassland or cool semi-desert regions (e.g., North American Great Plains or Great Basin). Also challenging are some scrub trees, such as juniper (<i>Juniperus</i> spp.) or mesquite (<i>Prosopis</i> spp.), which can form shrub-like stands, and are typically <5 m tall at maturity in parts of their range. Where forms are not easily defined, woody plants equal to or >5 m at maturity are considered trees (FGDC 2008). In the United States, there are shrubby junipers (<i>Juniperus communis, Juniperus pinchotii</i>) that should be treated as shrubs. But pygmy conifers can potentially make 5 m and are treated as trees (<i>Pinus edulis, Juniperus scopulorum, Juniperus monosperma, Juniperus occidentalis, Juniperus osteosperma</i>).<br /><br />There is a group of ephemerals that are generally mesomorphic, which can, under optimal rainfall conditions, grow on sand, including desert sands and pavement. They are adapted to deserts through their seed characteristics. Typically they do not occupy extensive deep shifting sands, only margins of sandsheets and more stable sands. They rely on seedbanks that may persist for decades in the sand and germinate under optimal winter or summer episodes of heavy rains. These are treated here as part of the mesomorphic shrub and herb class. Examples of psammophytic species include some sand verbenas (<i>Abronia</i> spp.) and several Asteraceae (e.g., <i>Dicoria canescens, Palafoxia</i> spp., etc.).',
   'Colloquial Name': 'Shrub & Herb Vegetation',
   'Diagnostic Characteristics': 'Shrubs and herbs in non-tropical savanna regions are at least 10% cover, mesomorphic trees &lt;10% cover, and the majority of cover is composed of mesomorphic shrub (<i>broad-leaved, needle-leaved, sclerophyllous</i>, and <i>rosette shrubs</i>) and herb (<i>forbs</i> and <i>graminoids</i>) growth forms compared to xeromorphic or cryomorphic shrub and herb growth forms. The vegetation structure has irregular horizontal canopy spacing. In tropical upland savanna regions, trees typically have up to 40% cover, are &lt;8 m tall, and the vegetation has a substantial graminoid layer.',
   'Formatted Scientific Name': 'Mesomorphic Shrub & Herb Vegetation Class',
   'Rationale': nan,
   'Scientific Name': 'Mesomorphic Shrub & Herb Vegetation Class',
   'Translated Name': 'Mesomorphic Shrub & Herb Vegetation Class',
   'Type Concept': 'Shrubs and herbs with broadly mesomorphic (including scleromorphic) growth forms (including <i>broad-leaved, needle-leaved</i>, and <i>sclerophyllous shrubs</i>, some types of <i>rosette shrubs</i>, and <i>forb</i> and <i>graminoid herbs</i>) dominate this type. Vegetation structure is typically moderately open to closed canopy, with irregular horizontal canopy spacing and variable height, but typically <5 m, and where mesomorphic trees have <10% cover and mesomorphic shrub and herb growth forms have the majority of cover compared to xeromorphic or cryomorphic growth forms. But in tropical upland savanna regions, trees may have up to 40% cover, are <8 m tall, and the vegetation has a substantial graminoid layer. Climates range from tropical humid to (seasonal) dry to boreal and subalpine, with fairly moderate moisture and temperature conditions. Substrate moisture conditions vary from dry to wet. Vegetation includes upland grasslands, shrublands, open tree savannas, wetland emergent marshes, bogs and fens.',
   'Type Concept Sentence': 'Grasslands, shrublands, open tree savannas, marshes, bogs and fens dominated by broadly mesomorphic (including scleromorphic) shrub and herb growth forms (including <i>broad-leaved, needle-leaved</i>, and <i>sclerophyllous shrubs</i>, and <i>forb</i> and <i>graminoid herbs</i>) with an irregular horizontal canopy structure, mesomorphic trees typically <10% cover (but tropical tree savannas typically <40%), tropical to boreal and subalpine climates, and wet to dry substrate conditions.'},
  'Vegetation': {'Physiognomy and Structure': '<i>Growth Forms</i>: Stands are dominated by any broadly mesomorphic (including scleromorphic) herb or shrub growth form, with or without a layer of nonvascular growth form (i.e., lichen, moss). Mesomorphic shrubs include <i>broad-leaved, needle-leaved, sclerophyllous</i>, and <i>palm shrubs</i>. Semi-shrubs are typically absent. Mesomorphic herbs include forbs (including <i>flowering forbs, ferns</i>, and <i>succulent forbs</i>) and <i>graminoids</i>. These herbaceous growth forms are not exclusive to the mesomorphic class, and more work is needed to assess whether additional herbaceous growth form types should be recognized that may be distinctive for this class.<br /><br /><i>Structure</i>: Stands have irregular shrub or herb horizontal stem spacing, typically with a moderately open to closed shrub or herb layer. There is <10% mesomorphic tree cover (<40% in tropical tree savannas), and the majority of shrub and/or herb growth forms are mesomorphic, typically exceeding 10% cover (but may be as low as 1-10% cover). Nonvascular and dwarf-shrub growth forms may vary from 0 to 100%, and tree seedlings or saplings may be present at any level of cover if they are below the predominant heights of the shrubs and herbs. At maturity, dominant shrubs and herbs are typically >0.3 m (sometimes over 5-10 m).'},
  '_id': 'ff521598-1297-492a-b4c0-95ece1919f3f'},
 {'Hierarchy': {'Classification Level ID': 101,
   'Hierarchy Level': 'Class',
   'parent_id': nan},
  'Identifiers': {'Classification Code': '3',
   'Database Code': 'C03',
   'Display Title': '3 Desert & Semi-Desert Class',
   'element_global_id': '860216'},
  'Overview': {'Classification Comments': 'In desert regions, the vegetation may be very sparse (at or below 1%). Some judgment is required to ensure how to sample and classify vegetation in stands where there is <1% vascular plant cover in parts, but not all, of the stand. That is, some deserts may have only patchy non-vegetated areas, whereas others may have extensive non-vegetated areas. More work is needed to define xeromorphic herbaceous growth forms, such as ephemerals, that may appear under rare high-precipitation years.<br /><br />Semi-desert grasslands may be hard to identify in this class when woody plants are absent or uncommon, because there are no herbaceous growth forms currently recognized that are diagnostic for the xeromorphic class. Desert grasses may be xerophytic but not clearly xeromorphic. However, in many cases they will have strong floristic similarity to open desert shrublands and, if degraded, may be dominated by desert shrubs. More work is needed to determine if such growth forms can be specified (e.g., desert-blooming ephemerals).',
   'Colloquial Name': 'Desert & Semi-Desert',
   'Diagnostic Characteristics': 'Xeromorphic tree (<i>succulent tree, small-leaved tree</i>) or shrub (<i>succulent shrub, small-leaved shrub</i>) growth forms have the majority of the cover compared to mesomorphic and cryomorphic shrub and herb growth forms, and mesomorphic trees have &lt;10% cover. The vegetation has irregular horizontal canopy spacing, and may be as low as 1% cover.',
   'Formatted Scientific Name': 'Xeromorphic Woodland, Scrub & Herb Vegetation Class',
   'Rationale': nan,
   'Scientific Name': 'Xeromorphic Woodland, Scrub & Herb Vegetation Class',
   'Translated Name': 'Xeromorphic Woodland, Scrub & Herb Vegetation Class',
   'Type Concept': 'Succulents, small-leaved shrubs and trees, desert grasses and other xeromorphic growth forms are dominant or characteristic in this type, which can include very open rocky or sandy desert types. Vegetation often has open and irregular horizontal canopy spacing, typically <5 m tall. Mesomorphic trees have <10% cover, and xeromorphic growth forms [including <i>succulent trees</i> and <i>shrubs</i> (e.g., cacti, euphorbias)] and <i>small-leaved shrubs</i> and <i>trees</i>, have the majority of cover compared to mesomorphic or cryomorphic growth forms. The herb cover varies from open to absent, with various growth forms, including ephemerals and <i>succulent forbs</i>. Climates include warm (tropical) to cool (temperate) arid to desert, with regular drought periods. Substrates are dry to moist, sometimes strongly haline-alkaline, or rarely, temporarily wet (e.g., desert washes). Vegetation includes cool and warm semi-deserts.',
   'Type Concept Sentence': 'Cool and warm semi-deserts dominated by xeromorphic growth forms, including <i>succulent</i> (e.g., cacti, euphorbias) and <i>small-leaved shrubs</i> and <i>trees</i>, desert grasses and other xeromorphic growth forms, with an irregular horizontal canopy spacing that is often open to very sparse (1%) cover.'},

In [68]:
bis = dd.getDB("bis")
nvcsCollection = bis["NVCS"]

In [70]:
nvcsCollection.delete_many({})
nvcsCollection.insert_many(nvcsUnits)